### ISSUE TITLE
Now working with yarn?

### ISSUE THREAD

**Issue by ebaynaud** [pingyhq/nm-prune#2]
```
$ yarn global add nm-prune
yarn global v1.2.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "nm-prune@1.1.1" with binaries:
      - nm-prune
✨  Done in 6.14s.

$ nm-prune
/Users/me/.config/yarn/global/node_modules/nm-prune/cli.js:35
);
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by davej** [comment]
What version of Node are you running?

**Comment by ebaynaud** [comment]
v6.11.4

**Comment by davej** [comment]
Seems to only work on Node 8+. That's a bug it should work on 6+, I'll look into it now.

**Comment by ebaynaud** [comment]
Yes indeed, not related to Yarn as NPM give same result:

```
$ nm-prune
/usr/local/lib/node_modules/nm-prune/cli.js:35
);
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by davej** [comment]
Fixed now. Publish as `v1.2.0`.
